openapi: 3.0.0
info:
  title: OpenSearch Traces API
  version: 0.1.0
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  /traces:
    get:
      summary: Get traces
      operationId: getTraces
      responses:
        200:
          description: A list of traces
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Traces'

components:
  schemas:
    Traces:
      type: object
      properties:
        traces:
          type: array
          items:
            $ref: '#/components/schemas/Trace'
    Trace:
      type: object
      properties:
        traceId:
          type: string
        spanId:
          type: string
        timestamp:
          type: string
          format: date-time
        name:
          type: string
