openapi: 3.0.0
info:
  title: OpenSearch Traces API
  version: 0.1.0
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  /traces:
    post:
      summary: Get traces from a given datasource
      operationId: getTraces
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetTracesRequest'
      responses:
        200:
          description: A list of traces
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Traces'

components:
  schemas:
    GetTracesRequest:
      type: object
      properties:
        url:
          type: string
        database:
          type: string
        timeField:
          type: string
    Traces:
      type: object
      properties:
        traces:
          type: array
          items:
            $ref: '#/components/schemas/Trace'
    Trace:
      type: object
      properties:
        traceId:
          type: string
        spanId:
          type: string
        timestamp:
          type: string
          format: date-time
        name:
          type: string
