services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    volumes:
      - ../provisioning/dashboards-local:/etc/grafana/provisioning/dashboards
    network_mode: host

networks:
  default:
