services:
  grafana:
    user: root
    container_name: 'gresearch-grafanaincrementaltraceviewer-viewer'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.6.3-security-01-ubuntu}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../dist:/var/lib/grafana/plugins/gresearch-grafanaincrementaltraceviewer-panel
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/gresearch-grafanaincrementaltraceviewer-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.gresearch-grafanaincrementaltraceviewer-app:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: gresearch-grafanaincrementaltraceviewer-panel
