/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get traces from a given datasource */
        post: operations["getTraces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GetTracesRequest: {
            url?: string;
            database?: string;
            timeField?: string;
        };
        Traces: {
            traces?: components["schemas"]["Trace"][];
        };
        Trace: {
            traceId?: string;
            spanId?: string;
            /** Format: date-time */
            timestamp?: string;
            name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getTraces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GetTracesRequest"];
            };
        };
        responses: {
            /** @description A list of traces */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Traces"];
                };
            };
        };
    };
}
export enum ApiPaths {
    getTraces = "/traces"
}
